# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OperatorBuilder < Formula
  desc "A Kubebuilder plugin to accelerate the development of Kubernetes operators."
  homepage "https://github.com/vmware-tanzu-labs/operator-builder"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.6.0/operator-builder_v0.6.0_Darwin_x86_64.tar.gz"
      sha256 "1b94920b763d3b4d51730f562ba38b1c335294eba786fec966db18e0c8759ffd"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.6.0/operator-builder_v0.6.0_Darwin_arm64.tar.gz"
      sha256 "565835dce89c201a998f16bae67b850a07944881b10a7bccb64ba6c8a089a48e"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.6.0/operator-builder_v0.6.0_Linux_x86_64.tar.gz"
      sha256 "d8208f05a7f672fdc5b96158eaa8ff29e6c5a71bb35a3eb123f3583d7ef717ed"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.6.0/operator-builder_v0.6.0_Linux_arm64.tar.gz"
      sha256 "74e57193d6c99da23ef0a95c0da014de739b6d1f85d2dce2156299c11a779498"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
  end

  depends_on "kubectl"
  depends_on "golang"
  depends_on "make" => :optional

  test do
    system "#{bin}/operator-builder version"
  end
end
