# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OperatorBuilder < Formula
  desc "A Kubebuilder plugin to accelerate the development of Kubernetes operators."
  homepage "https://github.com/vmware-tanzu-labs/operator-builder"
  version "0.3.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.3.0/operator-builder_v0.3.0_Darwin_arm64.tar.gz"
      sha256 "55aeb67efaef281416537d0d4340a3cd476790e248350a035dc06fbdc36af466"
    end
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.3.0/operator-builder_v0.3.0_Darwin_x86_64.tar.gz"
      sha256 "adf4c1165229ffdc72a8806a1a1e359b5a26f4b25d8507b9ac0bbce8bf10f47a"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.3.0/operator-builder_v0.3.0_Linux_arm64.tar.gz"
      sha256 "2a6fa742dfef150b0a7f33fc5f9abe1c861b2663f139c6a5290b99e87e12fbfb"
    end
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.3.0/operator-builder_v0.3.0_Linux_x86_64.tar.gz"
      sha256 "140fc0927a14177f6ed35e4d8614437893f1d5dea7c20b9db34ea024827e4289"
    end
  end

  depends_on "kubectl"
  depends_on "golang"
  depends_on "make" => :optional

  def install
    bin.install "operator-builder"
    bash_completion.install "completions/operator-builder.bash" => "operator-builder"
    zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
    fish_completion.install "completions/operator-builder.fish"
  end

  test do
    system "#{bin}/operator-builder version"
  end
end
