# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OperatorBuilder < Formula
  desc "A Kubebuilder plugin to accelerate the development of Kubernetes operators."
  homepage "https://github.com/vmware-tanzu-labs/operator-builder"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.5.1/operator-builder_v0.5.1_Darwin_x86_64.tar.gz"
      sha256 "b066a9292870d67e705d194e0fb8f13b07d07a1f3337d08af0f76e1e2d77c8e1"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.5.1/operator-builder_v0.5.1_Darwin_arm64.tar.gz"
      sha256 "509f97a945a663101310787ed9f0a4e50a0d3ddddc7e32cc0ae0c792b69508e6"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.5.1/operator-builder_v0.5.1_Linux_x86_64.tar.gz"
      sha256 "60803cc93be2a169e0eae95dee6daec388205de09fb0a11c98056e63b0ddd399"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vmware-tanzu-labs/operator-builder/releases/download/v0.5.1/operator-builder_v0.5.1_Linux_arm64.tar.gz"
      sha256 "83fa28e025f4dfb29bc03cf18ce499a05e221c576a5601c434d90fb0b564a581"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
  end

  depends_on "kubectl"
  depends_on "golang"
  depends_on "make" => :optional

  test do
    system "#{bin}/operator-builder version"
  end
end
