# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yot < Formula
  desc "A YAML Overlay Tool with templating tendencies."
  homepage "https://github.com/vmware-tanzu-labs/yaml-overlay-tool"
  version "0.6.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-labs/yaml-overlay-tool/releases/download/v0.6.3/yot_v0.6.3_Darwin_x86_64.tar.gz"
      sha256 "ac7e20d63668fd8ff86c9b6561d84c79288e9652a5d0c3dbda4482ef7c38df6d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/vmware-tanzu-labs/yaml-overlay-tool/releases/download/v0.6.3/yot_v0.6.3_Darwin_arm64.tar.gz"
      sha256 "02f90d9967e68a35b84139fc2a0574680de48f6e3bd1d56ec1fcf9a65f8dd5bb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-labs/yaml-overlay-tool/releases/download/v0.6.3/yot_v0.6.3_Linux_x86_64.tar.gz"
      sha256 "49e9ff9de72ce40efebfd2fecf45cc089f55a17e2d651b31b435229c85c67da2"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vmware-tanzu-labs/yaml-overlay-tool/releases/download/v0.6.3/yot_v0.6.3_Linux_arm64.tar.gz"
      sha256 "bd7abfabcb13be583775f935a7298b832334b8e85aa20841197e941877f77c7e"
    end
  end

  depends_on "kubectl" => :optional

  def install
    bin.install "yot"
    bash_completion.install "completions/yot.bash" => "yot"
    zsh_completion.install "completions/yot.zsh" => "_yot"
    fish_completion.install "completions/yot.fish"
  end

  test do
    system "#{bin}/yot --version"
  end
end
