# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yot < Formula
  desc "A YAML Overlay Tool with templating tendencies."
  homepage "https://github.com/vmware-tanzu-labs/yaml-overlay-tool"
  version "0.6.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-labs/yaml-overlay-tool/releases/download/v0.6.0/yot_v0.6.0_Darwin_x86_64.tar.gz"
      sha256 "b6d4ed6deae332c23f5d3ed7b73708253a268386045300648cfbe20b37829aa7"
    end
    if Hardware::CPU.arm?
      url "https://github.com/vmware-tanzu-labs/yaml-overlay-tool/releases/download/v0.6.0/yot_v0.6.0_Darwin_arm64.tar.gz"
      sha256 "2e4235274814d79cfa1f68afc595cff9acc2c49ab6dfd2292b53a86612252706"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-labs/yaml-overlay-tool/releases/download/v0.6.0/yot_v0.6.0_Linux_x86_64.tar.gz"
      sha256 "33202e40766743d77409aab5d78257b37e228276567804293788bfeb04841aab"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vmware-tanzu-labs/yaml-overlay-tool/releases/download/v0.6.0/yot_v0.6.0_Linux_arm64.tar.gz"
      sha256 "1b376c9f67821bc01ff5444ecbdb40ff88c40e4195eac5d265946935eb079f36"
    end
  end

  depends_on "kubectl" => :optional

  def install
    bin.install "yot"
    bash_completion.install "completions/yot.bash" => "yot"
    zsh_completion.install "completions/yot.zsh" => "_yot"
    fish_completion.install "completions/yot.fish"
  end

  test do
    system "#{bin}/yot --version"
  end
end
